// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantScores.Models;

namespace RestaurantScores.Migrations
{
    [DbContext(typeof(ReviewerScrpaingDetailsContext))]
    [Migration("20190423064906_ReviewerScrapingDetails")]
    partial class ReviewerScrapingDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("RestaurantScores.Models.ReviewerScrapingDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("NumberOfReviewsHtml");

                    b.Property<string>("NumberOfReviewsHtmlAttribute");

                    b.Property<int>("OverallMaxScore");

                    b.Property<string>("OverallScoreHtml");

                    b.Property<string>("OverallScoreHtmlAttribute");

                    b.Property<string>("WebAddress");

                    b.HasKey("Id");

                    b.ToTable("ReviewerScrapingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
